# Generated by Django 4.1 on 2022-04-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('display_ordering', models.IntegerField()),
                ('correct_ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('POPULARITY', 'Sort comments from most to least popular.'), ('REPLIES', 'Sort comments in order of reply.')], max_length=20)),
                ('post_text', models.TextField()),
            ],
        ),
    ]
