# Generated by Django 4.1 on 2022-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='post_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
